# Generated by Django 5.0 on 2023-12-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistmovie',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
