# Generated by Django 5.0 on 2023-12-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_watchlistmovie_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='service',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='theaters',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='watchlistmovie',
            name='IMDB',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='watchlistmovie',
            name='LBXD',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='watchlistmovie',
            name='MC',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='watchlistmovie',
            name='RTCritic',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='watchlistmovie',
            name='RTUser',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='watchlistmovie',
            name='TMDB',
            field=models.FloatField(null=True),
        ),
    ]
