# Generated by Django 5.0 on 2023-12-14 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_list_movielist_list_movies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movielist',
            options={'ordering': ['order']},
        ),
    ]
