# Generated by Django 5.0 on 2023-12-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0005_alter_movielist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='datetime_added',
            field=models.DateTimeField(null=True),
        ),
    ]
