# Generated by Django 5.0 on 2024-01-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0006_movie_datetime_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieactor',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
