# Generated by Django 5.0 on 2024-01-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0007_movieactor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistactor',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
