# Generated by Django 5.0 on 2024-01-23 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0008_watchlistactor_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'KEYWORDS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'TAGS',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='actor',
            name='gender',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='gender',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='bgLink',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='episodesSeen',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='seasonsSeen',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailerLink',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='watchlistmovie',
            name='bgLink',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='watchlistmovie',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='watchlistmovie',
            name='trailerLink',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='MovieKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.keyword')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.movie')),
            ],
            options={
                'db_table': 'MOVIE_KEYWORD',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='keywords',
            field=models.ManyToManyField(through='watchlist.MovieKeyword', to='watchlist.keyword'),
        ),
        migrations.CreateModel(
            name='WatchlistKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.keyword')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.watchlistmovie')),
            ],
            options={
                'db_table': 'WATCHLIST_KEYWORD',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='watchlistmovie',
            name='keywords',
            field=models.ManyToManyField(through='watchlist.WatchlistKeyword', to='watchlist.keyword'),
        ),
        migrations.CreateModel(
            name='WatchlistTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.watchlistmovie')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.tag')),
            ],
            options={
                'db_table': 'WATCHLIST_TAG',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='watchlistmovie',
            name='tags',
            field=models.ManyToManyField(through='watchlist.WatchlistTag', to='watchlist.tag'),
        ),
    ]
