# Generated by Django 5.0 on 2024-01-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0009_keyword_tag_actor_gender_director_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='avg_critical_rating',
            field=models.FloatField(null=True),
        ),
    ]
