# Generated by Django 5.0 on 2024-01-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0011_watchlistmovie_avg_critical_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='elo',
            field=models.FloatField(null=True),
        ),
    ]
