# Generated by Django 5.0 on 2024-01-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0012_movie_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='eloMatches',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
