# Generated by Django 5.0 on 2024-02-06 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0013_movie_elomatches'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='favorite',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'AWARDS',
                'managed': True,
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MovieAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.BooleanField()),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.award')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.movie')),
            ],
            options={
                'db_table': 'MOVIE_AWARD',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='awards',
            field=models.ManyToManyField(through='watchlist.MovieAward', to='watchlist.award'),
        ),
        migrations.CreateModel(
            name='MovieTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.movie')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.tag')),
            ],
            options={
                'db_table': 'MOVIE_TAG',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(through='watchlist.MovieTag', to='watchlist.tag'),
        ),
        migrations.CreateModel(
            name='WatchlistAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.BooleanField()),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.award')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.watchlistmovie')),
            ],
            options={
                'db_table': 'WATCHLIST_AWARD',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='watchlistmovie',
            name='awards',
            field=models.ManyToManyField(through='watchlist.WatchlistAward', to='watchlist.award'),
        ),
    ]
