# Generated by Django 5.0 on 2024-02-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0014_movie_favorite_award_movieaward_movie_awards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistmovie',
            name='favorite',
            field=models.BooleanField(null=True),
        ),
    ]
