# Generated by Django 5.0 on 2024-02-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0015_watchlistmovie_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
