import sys
sys.path.append(r"D:\Users\Max\MovieSite")

import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'MovieSite.settings')
django.setup()

import time
import random
import logging
import requests
import xml.etree.ElementTree as ET
from dotenv import load_dotenv
from slugify import slugify
from datetime import datetime
from watchlist.models import *
from watchlist.api_calls import *  
from watchlist.utils import get_trailer, get_keywords
from django.db import transaction, IntegrityError
import concurrent.futures
from django.db import transaction
from functools import partial
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from api_calls import get_TMDB_from_id
# from utils import make_api_calls_and_update_database, make_api_calls_and_update_watchlist, make_api_calls_and_update_database_from_id, getCast, process_actor

# make_api_calls_and_update_database("Disney Channel’s Theme A History Mystery", 2022, 5, "Went out of my way to find the proper documentation for this YouTube documentary done by Kevin Perjurer of Defunctland. One of the most artistic and well-done documentaries I've ever seen, and a beautiful conclusion in every way. Such a masterful way of cherishing and promoting art that deserves to be remembered.", None)

from watchlist.models import List, MovieList, Movie

# for item in [226979]:
#     dele = WatchlistMovie.objects.get(pk=item)
#     dele.delete()

def customPoster(id, link):
    movie = Movie.objects.get(pk=id)
    movie.posterLink = link
    movie.save()

# (200, 900) as defaults for scale of (1000, 1100, 1200, 1300, 1400, 1500, ...)
def defaultElo(scalingFactor, default):
    for movie in Movie.objects.filter(rating__isnull=False):
        movie.elo = (movie.rating * scalingFactor) + default
        # movie.elo = round(movie.elo, 2)
        print(f"{movie.title} ({movie.year}): {movie.elo}")
        movie.save()

def random_elo_match(movies, k, num):
    while num > 0:
        random_movies = random.sample(list(movies), 2)
        
        print(f"{random_movies[0].title} {random_movies[0].elo} vs. {random_movies[1].title} {random_movies[1].elo}")
        
        p1 = 1.0 / (1 + 10 ** ((random_movies[1].elo - random_movies[0].elo) / 400))
        p2 = 1.0 - p1
        
        response = input("1 or 2: ")
        
        if response == '1':
            update_elo(random_movies[0], random_movies[1], k, p1, p2)
        elif response == '2':
            update_elo(random_movies[1], random_movies[0], k, p2, p1)
        num = num - 1

def update_elo(winner, loser, k, pw, pl):
    winner.elo += round(k * (1 - pw), 2)
    loser.elo += round(k * (0 - pl), 2)
    
    print(f"{winner.title} {winner.elo} vs. {loser.title} {loser.elo}")
    
    winner.save()
    loser.save()

def correct_embed():
    for mov in Movie.objects.all():
        if "/watch/" in mov.trailerLink:
            new_url = mov.trailerLink.replace("/watch/", "/embed/")
            print(new_url)
            mov.trailerLink = new_url
            mov.save()
        else:
            print("The URL format is not as expected.")

def updateWatchlist():
    t1 = time.time()
    for mov in WatchlistMovie.objects.all():
        tmdb = get_TMDB_from_id(mov.TMDB_ID, mov.type)
        omdb = get_OMDB_from_id(mov.IMDB_ID)
        mov.posterLink = omdb['Poster']
        print(f"{mov.title} {mov.year}")
        mov.status = tmdb['status']
        mov.bgLink = f"https://image.tmdb.org/t/p/original{tmdb['backdrop_path']}"
        mov.trailerLink = f"https://youtube.com/embed/{get_trailer(tmdb)}"
        mov.save()
    print(f"Completed Watchlog update in {time.time()-t1} seconds")

def updateWatchlog():
    t1 = time.time()
    for mov in Movie.objects.all():
        print(f"{mov.title} at {time.time()-t1} seconds.")
        tmdb = get_TMDB_from_id(mov.TMDB_ID, mov.type)
        # omdb = get_OMDB(mov.IMDB_ID)
        # mov.posterLink = omdb['Poster']
        keywords = get_keywords(tmdb)
        if keywords:
            for k in keywords:
                print(k[1])
                key = Keyword(id=k[0], name=k[1])
                try:
                    key.save(using='library_db')
                except IntegrityError:
                    print('failed')
                    pass
                mov.keywords.add(key)
        mov.save()
    print(f"Completed Watchlog update in {time.time()-t1} seconds")

def delete_movie_actors_with_null_role():
    movie_actors_to_delete = MovieActor.objects.filter(role__isnull=True)
    movie_actors_to_delete.delete()

def delete_watchlist_actors_with_null_role():
    movie_actors_to_delete = WatchlistActor.objects.filter(role__isnull=True)
    movie_actors_to_delete.delete()

# make_api_calls_and_update_watchlist("Toy Story 4", 2019, None, "2023-12-06")
# make_api_calls_and_update_watchlist("Good Boys", 2019, None, "2023-12-06")
# make_api_calls_and_update_watchlist("Black Swan", 2010, None, "2023-12-04")
# make_api_calls_and_update_watchlist("Incendies", 2010, None, "2023-12-04")
# make_api_calls_and_update_watchlist("Dallas Buyers Club", 2013, None, "2023-12-04")
# make_api_calls_and_update_watchlist("Godzilla Minus One", 2023, None, "2023-12-03")
# make_api_calls_and_update_watchlist("Saltburn", 2023, None, "2023-12-01")
# make_api_calls_and_update_watchlist("Triangle of Sadness", 2022, None, "2023-11-20")
# make_api_calls_and_update_watchlist("King Richard", 2021, None, "2023-11-20")
# make_api_calls_and_update_watchlist("The King's Man", 2021, None, "2023-11-20")
# make_api_calls_and_update_watchlist("Kingsman: The Golden Circle", 2017, None, "2023-11-20")
# make_api_calls_and_update_watchlist("Kingsman: The Secret Service", 2014, None, "2023-11-20")
# make_api_calls_and_update_watchlist("Blue Beetle", 2023, None, "2023-11-20")
# make_api_calls_and_update_watchlist("Napoleon", 2023, None, "2023-11-20")
# make_api_calls_and_update_watchlist("Blackberry", 2023, None, "2023-11-20")
# make_api_calls_and_update_watchlist("Bottoms", 2023, None, "2023-11-20")
# make_api_calls_and_update_watchlist("M", 1931, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Citizen Kane", 1941, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Singin' in the Rain", 1952, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Vertigo", 1958, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("North by Northwest", 1959, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Lawrence of Arabia", 1962, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Once Upon a Time in America", 1984, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Amélie", 2001, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("The Hunt", 2012, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("The Great Dictator", 1940, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Sunset Blvd.", 1950, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Paths of Glory", 1957, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Witness for the Prosecution", 1957, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Dr. Strangelove", 1964, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("High and Low", 1963, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("The Shining", 1980, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Das Boot", 1981, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Raiders of the Lost Ark", 1981, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Amadeus", 1984, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Aliens", 1986, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Princess Mononoke", 1997, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Braveheart", 1995, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("American Beauty", 1999, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Memento", 2000, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Oldboy", 2003, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("The Lives of Others", 2006, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("3 Idiots", 2009, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Django Unchained", 2012, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Your Name.", 2016, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Capernaum", 2018, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("City Lights", 1931, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Modern Times", 1936, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Casablanca", 1942, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Psycho", 1960, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Once Upon a Time in the West", 1968, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Apocalypse Now", 1979, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Grave of the Fireflies", 1988, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Alien", 1979, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("Cinema Paradiso", 1988, "IMDB Poster", "2023-11-20")
# make_api_calls_and_update_watchlist("The Usual Suspects", 1995, "IMDB Poster", "2023-11-19")
# make_api_calls_and_update_watchlist("American History X", 1998, "IMDB Poster", "2023-11-19")
# make_api_calls_and_update_watchlist("The Prestige", 2006, "IMDB Poster", "2023-11-19")
# make_api_calls_and_update_watchlist("The Untouchables", 1987, "IMDB Poster", "2023-11-19")
# make_api_calls_and_update_watchlist("It's a Wonderful Life", 1946, "IMDB Poster", "2023-11-19")
# make_api_calls_and_update_watchlist("Seven Samurai", 1954, "IMDB Poster", "2023-11-19")
# make_api_calls_and_update_watchlist("Harakiri", 1962, "IMDB Poster", "2023-11-19")
# make_api_calls_and_update_watchlist("The Silence of the Lambs", 1991, "IMDB Poster", "2023-11-19")
# make_api_calls_and_update_watchlist("Terminator 2", 1991, "IMDB Poster", "2023-11-19")
# make_api_calls_and_update_watchlist("The Terminator", 1984, None, "2023-11-19")
# make_api_calls_and_update_watchlist("Se7en", 1995, "IMDB Poster", "2023-11-19")
# make_api_calls_and_update_watchlist("Life is Beautiful", 1997, "IMDB Poster", "2023-11-19")
# make_api_calls_and_update_watchlist("The Green Mile", 1999, "IMDB Poster", "2023-11-19")
# make_api_calls_and_update_watchlist("Saving Private Ryan", 1998, "IMDB Poster", "2023-11-19")
# make_api_calls_and_update_watchlist("City of God", 2002, "IMDB Poster", "2023-11-19")
# make_api_calls_and_update_watchlist("One Flew Over the Cuckoo's Nest", 1975, "IMDB Poster", "2023-11-19")
# make_api_calls_and_update_watchlist("The Good, the Bad, and the Ugly", 1966, "IMDB Poster", "2023-11-19")
# make_api_calls_and_update_watchlist("12 Angry Men", 1957, "IMDB Poster", "2023-11-19")
# make_api_calls_and_update_watchlist("Schindler's List", 1993, "IMDB Poster", "2023-11-19")
# make_api_calls_and_update_watchlist("The Godfather Part II", 1974, "IMDB Poster", "2023-11-19")
# make_api_calls_and_update_watchlist("The Godfather", 1972, "IMDB Poster", "2023-11-19")
# make_api_calls_and_update_watchlist("The Pianist", 2002, "Best Picture, IMDB Poster", "2023-11-16")
# make_api_calls_and_update_watchlist("Dicks: The Musical", 2023, None, "2023-11-15")
# make_api_calls_and_update_watchlist("Sully", 2016, None, "2023-11-15")
# make_api_calls_and_update_watchlist("The Power of the Dog", 2021, None, "2023-11-14")
# make_api_calls_and_update_watchlist("Yesterday", 2019, None, "2023-11-14")
# make_api_calls_and_update_watchlist("Rocketman", 2019, None, "2023-11-14")
# make_api_calls_and_update_watchlist("Vice", 2018, "Tik Tok", "2023-11-12")
# make_api_calls_and_update_watchlist("Downsizing", 2017, "Tik Tok", "2023-11-12")
# make_api_calls_and_update_watchlist("Paul Blart: Mall Cop 2", 2015, None, "2023-11-12")
# make_api_calls_and_update_watchlist("The American President", 1995, "Mom", "2023-11-08")
# make_api_calls_and_update_watchlist("Inglourious Basterds", 2009, "IMDB Poster", "2023-11-06")
# make_api_calls_and_update_watchlist("The Rat Catcher", 2023, None, "2023-10-29")
# make_api_calls_and_update_watchlist("Goodfellas", 1990, "IMDB Poster", "2023-10-29")
# make_api_calls_and_update_watchlist("Casino", 1995, None, "2023-10-29")
# make_api_calls_and_update_watchlist("Fight Club", 1999, "IMDB Poster", "2023-10-29")
# make_api_calls_and_update_watchlist("The Girl With the Dragon Tattoo", 2011, None, "2023-10-29")
# make_api_calls_and_update_watchlist("Gooby", 2009, "Gooby", "2023-10-29")
# make_api_calls_and_update_watchlist("Are You There God? It's Me Margaret", 2023, None, "2023-10-26")
# make_api_calls_and_update_watchlist("The Notebook", 2004, None, "2023-10-26")
# make_api_calls_and_update_watchlist("Fractured", 2019, "Abby", "2023-10-25")
# make_api_calls_and_update_watchlist("The Lovely Bones", 2009, "Abby", "2023-10-25")
# make_api_calls_and_update_watchlist("Queen's Gambit", 2020, "With Abby", "2023-10-20")
# make_api_calls_and_update_watchlist("Three Billboards Outside Ebbing, Missouri", 2017, "Tik Tok", "2023-10-15")
# make_api_calls_and_update_watchlist("Hacksaw Ridge", 2016, None, "2023-10-12")
# make_api_calls_and_update_watchlist("Zero Dark Thirty", 2012, None, "2023-10-12")
# make_api_calls_and_update_watchlist("Amsterdam", 2022, None, "2023-10-12")
# make_api_calls_and_update_watchlist("Ready Player One", 2018, "Schaffarillis", "2023-10-12")
# make_api_calls_and_update_watchlist("The Invention of Lying", 2009, "Tik Tok", "2023-10-12")
# make_api_calls_and_update_watchlist("What We Do in the Shadows", 2014, "Nando v Movies", "2023-10-12")
# make_api_calls_and_update_watchlist("Us", 2019, "With Abby", "2023-10-08")
# make_api_calls_and_update_watchlist("The Black Phone", 2021, None, "2023-10-08")
# make_api_calls_and_update_watchlist("The Martian", 2015, None, "2023-10-04")
# make_api_calls_and_update_watchlist("Blade Runner", 1982, "Colton, Gaven", "2023-10-04")
# make_api_calls_and_update_watchlist("The Voyeurs", 2021, "Tik Tok", "2023-10-04")
# make_api_calls_and_update_watchlist("The Meyerowitz Stories", 2017, "Adam Sandler", "2023-10-03")
# make_api_calls_and_update_watchlist("Enemy", 2014, None, "2023-10-03")
# make_api_calls_and_update_watchlist("Snowpiercer", 2013, "Bong Joon Ho", "2023-10-03")
# make_api_calls_and_update_watchlist("Drive", 2011, "Ryan Gosling", "2023-10-03")
# make_api_calls_and_update_watchlist("First Man", 2018, "Ryan Gosling, Damien Chazelle", "2023-10-03")
# make_api_calls_and_update_watchlist("The Boy and the Heron", 2023, "Ghibli", "2023-09-25")
# make_api_calls_and_update_watchlist("Ferrari", 2023, "2024 Oscars", "2023-09-25")
# make_api_calls_and_update_watchlist("The Zone of Interest", 2023, "2024 Oscars", "2023-09-25")
# make_api_calls_and_update_watchlist("Poor Things", 2023, "2024 Oscars", "2023-09-25")
# make_api_calls_and_update_watchlist("Killers of the Flower Moon", 2023, "2024 Oscars", "2023-09-25")
# make_api_calls_and_update_watchlist("American Fiction", 2023, "2024 Oscars", "2023-09-25")
# make_api_calls_and_update_watchlist("Maestro", 2023, "2024 Oscars", "2023-09-25")
# make_api_calls_and_update_watchlist("The Marvels", 2023, "MCU", "2023-09-25")
# make_api_calls_and_update_watchlist("St. Elmo's Fire", 1985, "Mom", "2023-09-25")
# make_api_calls_and_update_watchlist("Raising Arizona", 1987, None, "2023-09-25")
# make_api_calls_and_update_watchlist("Léon: The Professional", 1994, "Andrew, IMDB Poster ", "2023-09-11")
# make_api_calls_and_update_watchlist("Past Lives", 2023, None, "2023-09-11")
# make_api_calls_and_update_watchlist("Perfect Blue", 1997, "With Abby", "2023-09-06")
# make_api_calls_and_update_watchlist("Kill Bill Vol. 1", 2003, "Abby", "2023-08-24")
# make_api_calls_and_update_watchlist("Kill Bill Vol. 2", 2004, "Abby", "2023-08-24")
# make_api_calls_and_update_watchlist("Scarface", 1983, "Classic", "2023-08-24")
# make_api_calls_and_update_watchlist("2001: A Space Odyssey", 1968, "IMDB Poster", "2023-08-24")
# make_api_calls_and_update_watchlist("Watchmen", 2009, None, "2023-08-24")
# make_api_calls_and_update_watchlist("No Country for Old Men", 2007, "Best Picture", "2023-08-24")
# make_api_calls_and_update_watchlist("Top Gun: Maverick", 2022, None, "2023-08-24")
# make_api_calls_and_update_watchlist("Finch", 2021, None, "2023-08-24")
# make_api_calls_and_update_watchlist("A Bug's Life", 1998, "Pixar", "2023-08-24")
# make_api_calls_and_update_watchlist("Lightyear", 2022, "Pixar", "2023-08-24")
# make_api_calls_and_update_watchlist("Spies in Disguise", 2019, "Bluesky", "2023-08-24")
# make_api_calls_and_update_watchlist("The Good Dinosaur", 2015, "Pixar", "2023-08-24")
# make_api_calls_and_update_watchlist("Avatar: The Way of Water", 2022, None, "2023-08-24")
# make_api_calls_and_update_watchlist("Akira", 1988, None, "2023-08-24")
# make_api_calls_and_update_watchlist("Another Round", 2020, "The Yard, Music", "2023-08-24")
# make_api_calls_and_update_watchlist("Bohemian Rhapsody", 2018, None, "2023-08-24")
# make_api_calls_and_update_watchlist("Pinball: The Man who Saved the Game", 2022, None, "2023-08-24")
# make_api_calls_and_update_watchlist("We're the Millers", 2013, "Tik Tok", "2023-08-24")
# make_api_calls_and_update_watchlist("Return of the King", 2003, "Best Picture, LoTR", "2023-08-24")
# make_api_calls_and_update_watchlist("The Lord of the Rings: The Two Towers", 2002, "LoTR, IMDB Poster", "2023-08-24")
# make_api_calls_and_update_watchlist("Chicago", 2002, "Best Picture", "2023-08-24")
# make_api_calls_and_update_watchlist("Howl's Moving Castle", 2004, "Ghibli", "2023-08-24")
# make_api_calls_and_update_watchlist("I, Tonya", 2017, None, "2023-08-24")
# make_api_calls_and_update_watchlist("Jennifer's Body", 2009, "Tik Tok", "2023-08-24")
# make_api_calls_and_update_watchlist("Juno", 2007, "Tik Tok", "2023-08-24")
# make_api_calls_and_update_watchlist("Kiki's Delivery Service", 1989, "Ghibli", "2023-08-24")
# make_api_calls_and_update_watchlist("My Neighbor Totoro", 1988, "Ghibli", "2023-08-24")
# make_api_calls_and_update_watchlist("Slumdog Millionaire", 2008, "Best Picture", "2023-08-24")
# make_api_calls_and_update_watchlist("Space Jam: A New Legacy", 2021, None, "2023-08-24")
# make_api_calls_and_update_watchlist("The Artist", 2011, "Best Picture", "2023-08-24")
# make_api_calls_and_update_watchlist("The French Dispatch", 2021, None, "2023-08-24")
# make_api_calls_and_update_watchlist("The Lord of the Rings: The Fellowship of the Ring", 2001, "LoTR, IMDB Poster", "2023-08-24")
# make_api_calls_and_update_watchlist("The Matrix", 1999, "Matrix, IMDB Poster", "2023-08-24")
# make_api_calls_and_update_watchlist("The Matrix Reloaded", 2003, "Matrix", "2023-08-24")
# make_api_calls_and_update_watchlist("The Matrix Revolutions", 2003, "Matrix", "2023-08-24")
# make_api_calls_and_update_watchlist("12 Years a Slave", 2013, "Best Picture", "2023-08-24")
# make_api_calls_and_update_watchlist("A Star Is Born", 2018, "Music", "2023-08-24")
# make_api_calls_and_update_watchlist("Argo", 2012, "Best Picture", "2023-08-24")
# make_api_calls_and_update_watchlist("Baby Driver", 2017, None, "2023-08-24")
# make_api_calls_and_update_watchlist("Donnie Darko", 2001, None, "2023-08-24")
# make_api_calls_and_update_watchlist("Dunkirk", 2017, None, "2023-08-24")
# make_api_calls_and_update_watchlist("Green Book", 2018, "Best Picture", "2023-08-24")
# make_api_calls_and_update_watchlist("Inception", 2010, "IMDB Poster", "2023-08-24")
# make_api_calls_and_update_watchlist("Jojo Rabbit", 2019, None, "2023-08-24")
# make_api_calls_and_update_watchlist("Little Women", 2019, None, "2023-08-24")
# make_api_calls_and_update_watchlist("Million Dollar Baby", 2004, "Best Picture", "2023-08-24")
# make_api_calls_and_update_watchlist("Mission: Impossible - Dead Reckoning Part One", 2023, "Mission: Impossible", "2023-08-24")
# make_api_calls_and_update_watchlist("Once Upon a Time... in Hollywood", 2019, None, "2023-08-24")
# make_api_calls_and_update_watchlist("Oppenheimer", 2023, None, "2023-08-24")
# make_api_calls_and_update_watchlist("Rush Hour", 1998, "Andrew", "2023-08-24")
# make_api_calls_and_update_watchlist("The Shape of Water", 2017, "Best Picture", "2023-08-24")
# make_api_calls_and_update_watchlist("The Shawshank Redemption", 1994, "IMDB Poster", "2023-08-24")
# make_api_calls_and_update_watchlist("The Whale", 2022, None, "2023-08-24")
# make_api_calls_and_update_watchlist("All Quiet on the Western Front", 2022, None, "2023-08-24")
# make_api_calls_and_update_watchlist("Guillermo Del Toro's Pinocchio", 2022, None, "2023-08-24")
# make_api_calls_and_update_watchlist("The Departed", 2006, "Best Picture, IMDB Poster", "2023-08-24")
# make_api_calls_and_update_watchlist("The Devil All the Time", 2020, None, "2023-08-24")
# make_api_calls_and_update_watchlist("The Irishman", 2019, None, "2023-08-24")
# make_api_calls_and_update_watchlist("Mission: Impossible", 1996, "Mission: Impossible", "2023-08-24")
# make_api_calls_and_update_watchlist("Mission: Impossible - Fallout", 2018, "Mission: Impossible", "2023-08-24")
# make_api_calls_and_update_watchlist("Mission: Impossible - Ghost Protocol", 2011, "Mission: Impossible", "2023-08-24")
# make_api_calls_and_update_watchlist("Mission: Impossible - Rogue Nation", 2015, "Mission: Impossible", "2023-08-24")
# make_api_calls_and_update_watchlist("Mission: Impossible II", 2000, "Mission: Impossible", "2023-08-24")
# make_api_calls_and_update_watchlist("Mission: Impossible III", 2006, "Mission: Impossible", "2023-08-24")
# make_api_calls_and_update_watchlist("Top Gun", 1986, "Classic", "2023-08-24")

# make_api_calls_and_update_database_from_id("tt5755238", 2.5, None, 0, '2023-11-23', 'Netflix')
# make_api_calls_and_update_database("Brave", 2012, 3.5, None, "2023-12-08")
# make_api_calls_and_update_database("The Big Lebowski", 1998, 4, None, "2023-12-08")
# make_api_calls_and_update_database("Raya and the Last Dragon", 2021, 3, "Respectfully, Nimona clears by a mile. The characters were kinda unlikable and the settings was clunky and didn'd really make sense. It had its moments, but it just wasn't very cohesive or strong.", "2023-12-07")
# make_api_calls_and_update_database("Strange World", 2022, 3.5, None, "2023-12-06")
# make_api_calls_and_update_database("Dune", 2021, 4.5, "God damn it I liked Dune. It was slow, but it felt like the pacing was earned. Honestly it felt like a better Star Wars movie than Star Wars does. That's my takeaway.", "2023-12-06")
# make_api_calls_and_update_database("The Holdovers", 2023, 4, None, "2023-12-04")
# make_api_calls_and_update_database("Zootopia", 2016, 4, None, "2023-12-04")
# make_api_calls_and_update_database("Requiem for a Dream", 2000, 4, "Score goes absolutely stupid, obviously. Work of art film that definitley didn't keep me locked all -the-way in, but there's no denying what it is.", "2023-12-03")
# make_api_calls_and_update_database("May December", 2023, 3.5, "Good but not excellent. Strong performances pushed what was honestly a very distracted narrative. The entire "'movie'" element just took away from the larger project in the end.  The scene where Charles Melton breaks down after sleeping with Natalie Portman's character felt like we finally saw just how awful this whole thing was, but it just didn't pay off enough for me in the end. I wanted a little more once they "'collapsed'" like that, and it just didn't get there for me.", "2023-12-02")
# make_api_calls_and_update_database("John Wick: Chapter 4", 2023, 3.5, "I really didn't expect him to straight up die at the end. How the fuck did Winston live through all 4 movies also, like what the hell. We'll see if his death sticks. This was probably the best "'movie'" overall, but it's still a John Wick movie y'know, leaves something to be desired.", "2023-12-01")
# make_api_calls_and_update_database("Dream Scenario", 2023, 3.5, "Fuckin weird ass, oddly somber ass movie.", "2023-11-30")
# make_api_calls_and_update_database("John Wick: Chapter 3 - Parabellum", 2019, 3, None, "2023-11-29")
# make_api_calls_and_update_database("John Wick: Chapter 2", 2017, 3.5, "Better than the first. Definitley still feels a little too ridiculous and one-note at times, but definitley a better overall film.", "2023-11-28")
# make_api_calls_and_update_database("John Wick", 2014, 3, None, "2023-11-27")
# make_api_calls_and_update_database("Good Will Hunting", 1997, 4.5, None, "2023-11-25")
# make_api_calls_and_update_database("Leo", 2023, 2.5, None, "2023-11-23")
# make_api_calls_and_update_database("Arrival", 2016, 5, None, "2023-11-23")
# make_api_calls_and_update_database("Tár", 2022, 4.5, "Really good in the fucked up and scary but without ever being overtly scary kinda way. Unbelievably good performance from Cate Blanchett, and a truly disturbing look at the role of ego and manipulation from a position of power.", "2023-11-22")
# make_api_calls_and_update_database("The Banshees of Inisherin", 2022, 3.5, "It's good in the 'Manchester By the Sea' kind of way, only I just didn't really like it as much as Manchester by the Sea.", "2023-11-22")
# make_api_calls_and_update_database("Blades of Glory", 2007, 3.5, None, "2023-11-20")
# make_api_calls_and_update_database("Please Don't Destroy: The Treasure of Foggy Mountain", 2023, 3, "Silly ass movie. I liked it, it was funny. It barely told a cohesive story that mattered, but it didn't really need to either.", "2023-11-20")
# make_api_calls_and_update_database("The King's Speech", 2010, 4, "The setting and such really isn't my style, but it's a damn good movie man.", "2023-11-20")
# make_api_calls_and_update_database("Inside Out", 2015, 4, "Made me cry. Little bit when Bing Bong died but then it just kept going for some reason. It was a good movie even if the characters were (obviously) super duper one-diensional.", "2023-11-18")
# make_api_calls_and_update_database("Eternal Sunshine of the Spotless Mind", 2004, 4.5, "I enjoyed the film, there were parts that lost me a little bit here and there, but the overall narrative was fantastic.", "2023-11-17")
# make_api_calls_and_update_database("The Peanut Butter Falcon", 2019, 5, "Man I really loved this movie. Good performances, good heartwarming story. Just good. I don't really think I have a real complaint.", "2023-11-17")
# make_api_calls_and_update_database("Zodiac", 2007, 4.5, "Honestly if I had known more about the whole Zodiac story going in, maybe my impression of the movie would've been different, but I was completely engulfed in the entire movie. The only thing I thought was done poorly was the depictions of the Zodiac killing the victims. Those scenes just lacked weight for some reason.", "2023-11-16")
# make_api_calls_and_update_database("Sound of Metal", 2019, 4.5, "Thank god Riz Ahmed was able to redeem himself after I saw Fingernails before this. Really good movie, I teared up 40 mins in, and the whole film just had so much weight to it. The ending left a little bit to be desired, and I really thought it was aiming towards him going back to the deaf community at the end... which I felt it implied, but I wouldn't have hated to see it too.", "2023-11-15")
# make_api_calls_and_update_database("Pulp Fiction", 1994, 4, "I get why this movie is so good. I do not get why Quentin Tarantino casts himself in it...", "2023-11-15")
# make_api_calls_and_update_database("Loki", 2021, 4.5, None, "2023-11-15")
# make_api_calls_and_update_database("Worth", 2020, 4, "I sure do love when Michael Keaton plays some form of office boss burdened with impossible weight of tragedy.", "2023-11-14")
# make_api_calls_and_update_database("Gone Girl", 2014, 4.5, "I have no idea how or why, but for some reason I internally knew the entire plot of this movie.", "2023-11-13")
# make_api_calls_and_update_database("The Wolf of Wall Street", 2013, 4, "First Scorcese film I've seen. At times the whole movie felt a little too full of itself, if that makes sense. It was a very good movie, with very good performances, but the story went everywhere all at once sometimes.", "2023-11-12")
# make_api_calls_and_update_database("The Killer", 2023, 3, "I was just very very bored for most of the movie. I feel like the first 30-40mins lost me, and nothing ever felt interesting enough to draw me back.", "2023-11-12")
# make_api_calls_and_update_database("Sicario Day of the Soldado", 2018, 3, "Nothing really happened except for weird CIA/US Military self suck. Benicio Del Toro is moderately interesting, but the movie itself was very boring without the sort of 'mystery' of the first one. None of the characters do pretty much anything that expands upon their depiction in the first film, and largely they felt less interesting. I don't think it was an enormous step down from the first title, the narrative was a little tighter and as a stand alone action film it wasn't awful, but it just felt like a whole lot of nothing, and barely a sequel to the first. The events and characters of the first could've never existed and I wouldn't have known any better.", "2023-11-08")
# make_api_calls_and_update_database("I Think you Should Leave", 2019, None, None, "2023-11-08")
# make_api_calls_and_update_database("Hidden Figures", 2016, 4, "Really good movie. Taraji P. Henson gave a phenomonal performance.", "2023-11-08")
# make_api_calls_and_update_database("Now You See Me 2", 2016, 2.5, "Solid sequel, the characters were genuinely much better than in the first film, although the plot was definitley a little less interesting.  Lizzy Caplan's being cast to replace Isla Fisher worked really well, and it made the cast feel a lot more comedic as a whole. The movie at large was a downgrade, but I did enjoy the recast. If they ever get around to making a third one, I'll definitley check it out.", "2023-11-07")
# make_api_calls_and_update_database("Now You See Me", 2013, 3, "Interesting enough movie, the twist wasn't bad, but the characters were pretty uninteresting the entire time, though. The entire relationship with the French girl felt totally pointless, and the whole Four Horeseman group didn't really get enough attention either. It was weird because it feels like there was a way better movie trapped inside of this, it just bogged itself down with a lot of stupid shit. I had fun, and it wasn't awful, but it sincerely confused the shit out of me how close it was to being really good.", "2023-11-07")
# make_api_calls_and_update_database("The Social Network", 2010, 4.5, "One of the better 'historical retelling' type films. Justin Timberlake and Andrew Garfield really sold their performances, and Jesse Eisenberg was phenomonaly unlikable.", "2023-11-06")
# make_api_calls_and_update_database("Quiz Lady", 2023, 3, "Sold little movie. Nothing especially deep to analyze, just an enjoyable film that did everything it wanted to do. Awkwafina is funny, the movie was funny, it works.", "2023-11-06")
# make_api_calls_and_update_database("Fantastic Mr. Fox", 2009, 4, "Definitley felt like the most easily-digestable of Wes Anderson's works. I enjoyed the movie, it is just flatout good. I don't think there's a moment I look back on as exceptional specifically, but it was just good all around.", "2023-11-05")
# make_api_calls_and_update_database("Fingernails", 2023, 2, "Alright what if we made a love story where the entire plot is centered around ripping out your fingernails to take a scientific test that proves you're in love, only to end up glorifying cheating on your partner who you have an established and happy romance with for someone 'new' even though the movie makes a BIG deal about how love (in this world) can be statistically proven and we can see our protagonist is making the incorrect choice. There was never any strong depiction of Ryan being a bad boyfriend to Anna, and there was hardly any romance with Amir either that made it seem like she was supposed to be wth him. I don't understand how you can make a love story revolving around your most unlikable character and then expect it to be a good climax when she tears out her fingernails as a big 'statement' and cheats on her boyfriend who we've seen do nothing wrong. Absolutely bafflingly dumb storytelling. I don't understand it at all. Literally the only good thing that happened in the entire movie was Jeremy Allen White getting mad at someone, because by god that dude can yell on camera like nobody else, truly.", "2023-11-05")
# make_api_calls_and_update_database("Ted Lasso", 2020, 4.5, "Crushed that shit in 4 days. Great show, manages to tie together legitimate emotional moments and serious topics into a very funny show. Bummed that it's over but I was happy with most of the resolutions.", "2023-11-03")
# make_api_calls_and_update_database("Hoosiers", 1986, None, None, None)
# make_api_calls_and_update_database("Reservoir Dogs", 1992, 4, "Really cool film, even with a set limited to basically one room, the film never lost any tension or stakes. You never really trusted anyone or knew what was going to happen, and the ultimate result really encapsulated the noir style to the best of my understanding. Everythng sucked and no one lived happily ever after.", "2023-10-31")
# make_api_calls_and_update_database("Five Nights at Freddy's", 2023, 2, "Not very good. I feel like they should've either leaned into the campyness, or committed to making a legitimate horror film. Ultimately it wasn't scary, it made very little cohesive sense, and Matthew Lillaird was the only above-average thing in the movie. Bummer, because I feel like the concept could've been much better than it was.", "2023-10-29")
# make_api_calls_and_update_database("Willy Wonka & the Chocolate Factory", 1971, None, None, None)
# make_api_calls_and_update_database("The Wonderful Story of Henry Sugar", 2023, 4, "Genuinely did not expect this to be so good wow. I really liked it actually, the classic Wes Anderson cinemetography somehow felt dialed up even more than in one of his full-length projects. I think the artistic complexity of Anderson's work makes it incredibly difficult to rate against traditional film, because it feels like its own category. Ultimately I liked the short film, it wasn't my favorite film of all time, but it was oh so much better than I thought it would be.", "2023-10-28")
# make_api_calls_and_update_database("The Vow", 2012, 2.5, None, "2023-10-26")
# make_api_calls_and_update_database("Lady Bird", 2017, 4, "I really liked it, but I don't think I ever really fell in love with the movie as a whole, even though I really wanted to. There was some *really* good lines, 'but do you like me' hits so unbelievably hard. I felt myself close to tears a half dozen times, but I just couldn't get all the way there, and the ending, while really bittersweet in the best way, really did leave me wishing for something different.", "2023-10-25")
# make_api_calls_and_update_database("No Hard Feelings", 2023, 3, "Omg cousin!!!", "2023-10-23")
# make_api_calls_and_update_database("The Gray Man", 2022, 3.5, "Pretty much felt like a Ryan Gosling superhero movie. Honestly pretty tonally similar to the Russo's Marvel work. I really couldn't buy Chris Evans as a villain, he just isn't that guy. I liked that Gosling had some humor and his character was pretty well developed. The plot was pretty empty but the cinematography and fight coreo felt like more of a focus anyway. Average movie that was elevated by an entertaining lead performance.", "2023-10-19")
# make_api_calls_and_update_database("Ride the Eagle", 2021, 2.5, "Pretty unremarkable. Jake Johnson wasn't particularly funny which was a let down. The writing at points took me out of it, the dialogue just didn't feel human at a lot of points;. The last 30-40mins of the movie are pretty good, but it took a long time to find its footing.", "2023-10-18")
# make_api_calls_and_update_database("A Quiet Place: Part II", 2020, 3.5, "Not as good as the first, but not by much. The ending was a little frustrating and unsatisfactory, but it had some legit strengths. The opening showing 'Day 1' might've been the best part through, unfortunately.", "2023-10-17")
# make_api_calls_and_update_database("Focus", 2015, 3, "The entire plot of this movie was what a man would give up for Margot Robbie. The 'twist' wasnt half bad, and there were a couple of fairly memorable scenes. Slightly above average movie, but really just slight. Not especially inspiring writing or dialogue at all.", "2023-10-17")
# make_api_calls_and_update_database("Spotlight", 2015, 5, "An incredibly interesting true story that was delivered in a fantastic way. Great performances from Mark Ruffalo and Rachel McAddams headlined an excellent narrative re-telling of a story that, despite its prominence, was completely new to my ears. The film did an excellent job of showing what important work the Spotlight reporters did without making them seem like characters. They were human, delibrately so. The 9/11 disruption of course altered the pacing of the movie, but with historical accuracy in mind, that was important.", "2023-10-16")
# make_api_calls_and_update_database("Two Distant Strangers", 2020, None, None, None)
# make_api_calls_and_update_database("A Quiet Place", 2018, 3.5, "Too quiet!", "2023-10-13")
# make_api_calls_and_update_database("Mad Max: Fury Road", 2015, 3.5, "Solidly "'good'" movie. Honestly wasn't much for most of the cast, and I thought Max & Furiosa were weak characters generally. Nux's death was impressively emotional, honestly, but beyond that there was pretty limited depth. Not a ton of complaints. Super cool environments and cars and all that shit.", "2023-10-13")
# make_api_calls_and_update_database("The Hurt Locker", 2008, 4, "At some point in the movie I stopped being annoyed that Jeremy Renner was in it, which was impressive in and of itself.", "2023-10-11")
# make_api_calls_and_update_database("BlacKkKlansman", 2018, 4, "136 minutes of Adam Driver being allowed to use slurs", "2023-10-10")
# make_api_calls_and_update_database("Blade Runner 2049", 2017, 3.5, "Probably would've liked it a little more if I'd seen the original. It was good, but sincerely just not my genre or my style. Neo-Noir dystopian future just isn't my preferred setting, and it was difficult for me to take the portions with Ana de Armas very seriously given the whole e-girlfriend thing. I don't think Dennis Villeneuve's general filmmaking style is really my thing, honestly. So much of the movie ended up feeling kind of empty, visually, which I wasn't anticipating. Good narrative, good storytelling, just not my favorite film.", "2023-10-09")
# make_api_calls_and_update_database("Gladiator", 2000, 4, "Good movie, pretty long and slow at points though. Russel Crowe was good, and Jaoquin Phoenix was solid. All in allit was a solid historical epic., that's kinda all I have to say.", "2023-10-08")
# make_api_calls_and_update_database("Marriage Story", 2019, 5, "Truly a great love story that plays out in reverse. I don't know where my fondness for love stories where things don't work out comes from, but add this one to the list. Career-best performances from both leads, and just a brutal story where you can really feel the emotion behind the characters. Charlie's life is obllterated in seconds, and everything is moving too quickly for him to stop it, while Nicole is so desperate to re-claim the life she always wanted. Made my cry, and made me feel so much emotion for the characters. You could truly feel that the they still loved each other, even if it didn't make sense anymore.", "2023-10-05")
# make_api_calls_and_update_database("Manchester By the Sea", 2016, 4, "An incredibly somber and human film. It truly felt like the most depressing slice-of-life you've ever seen. The characters were compelling, but I was left wanting just a little bit more. It felt like I watched the first two acts to a fim that never quite got all the way there. I recognize that there wasn't really supposed to be a "'win'" at the end, but it felt like we were building towards Lee finally being okay back in Manchester, and we just never got that payoff. Intentional as it may be, it just felt unsatisfying.", "2023-10-03")
# make_api_calls_and_update_database("Sicario", 2015, 3.5, "A film that bravely lets Benicio Del Toro shoot children. Some great elements but I was a bit lost in all of it. I think it was all a bit too "'real'" and went over my head a little bit. I ended up with very little understanding of what I shoul take away, or really of what happened throughout the film. Del Toro and Josh Brolin were standouts, but Emily Blunt was just fine, it just felt like I was watching Emily Blunt, not her character. Sicaro was a visceral film, and it certainly built up suspense throughout, I just didn't feel like it paid off as well as I was anticipating, and the back half of the movie left me with more questions than answers.", "2023-10-03")
# make_api_calls_and_update_database("Judas and the Black Messiah", 2021, 3.5, "I find it really difficuly to rate movies that are telling true stories. It makes it difficult to really asses the "'plot'" or any story direction, because so much of it is true to life.  There weren't alot of standout moments in this movie really. The cinematography was fine, and the story was compelling certainly. Lakieth Stanfield was very good, although I did find it funny that he was once again depicting a guy who crosses the picket fence in some sense.", "2023-10-03")
# make_api_calls_and_update_database("The Nice Guys", 2016, 4.5, "I don't know that it did anything that was especially extraordinary, but it was funny, it was entertaining, and it had a compelling narative. Ryan Gosling and Russel Crowe were great and probably the only thing really worth remembering from the entire film, but that's okay. It made me laugh out loud alone in my room more than once, which it deserves lots of credit for.", "2023-10-02")
# make_api_calls_and_update_database("The Lego Batman Movie", 2017, 4.5, "Incredibly silly, but without sacrificing the opportunity to tell a meaningful story. Found family is a little played out, especially amidst Superheros, but the sheet light-heartedness of the entire movie juxtaposed with a very sincere theme and message made it really stick. The Lego Movies never miss, and this was not only a great Lego Movie, it was a fantastic Batman film as well.", "2023-09-30")
# make_api_calls_and_update_database("Joker", 2019, 2.5, "I understand being uncomfortable is kinda the whole point, but this entire film just wasn't for me. I recognize there were elements of good film-making at play, but the entire experience was just uncomfortable and made me bored. The ending, specifically the talk show scene, was fine, but it took so long to get there, and even to get through it, and I just wasn't enjoying it for most of that time. All of the Bruce Wayne tie-ins made me roll my eyes. Maybe I'm a little "'Jokered-out'" but I just didn't connect much to the message. It felt like a film that was so desprately trying to say something profound, but completely giving up any chance of doing so by tying it to a comic book villain. Just not my thing.", "2023-09-28")
# make_api_calls_and_update_database("The Batman", 2022, 4.5, "I liked The Batman wayyyyy more than I thought I would. It manages to be a legitimately good dramatic film for the most part. Batman stuff will always be cheesy at points, and shoe-horning in a teaser for the Joker at the end frustrated me, but I was able to take the Batman seriously through most of the movie, which is an accomplishment itself. Zoe Kravits had the best Catwoman portrayal on film without question, but she stands alone as far as characters that clearly exceed their "'Dark Knight'" counterparts. Robert Pattionson's Batman was good, at nothing else it felt distinct from Christian Bale, but I will struggle to ever see anyone but Bale as Bruce Wayne. Paul Dano's Riddler was actually very good, arguably the best part of the entire movie, boasting a compelling scheme and a very dark twist to the character. The stand-out element of the film was easily the cinematography. There are multiple shots and sequences, such as the gun-lit hallway fight scene, the car chase, and the flare-lit stadium, that are absolutely brilliant, and the costume design to "'noir-ify'" the villains was top-notch as well. The Batman probably looks better than it was, but I enjoyed the hell out of it regardless.", "2023-09-26")
# make_api_calls_and_update_database("The Machine", 2023, 3, "Honestly there was some weirdly good film-making and shot composition that was really misplaced in this movie. Like some of the transitions and lighting were way better than deserved. Jimmy Tatro was great as young Bert, and the story was fun and pretty average. Made me laugh plenty but not a ton. Bert was absolutely not a good actor in this movie, but it wasn't SO bad that it really hurt the fim.", "2023-09-24")
# make_api_calls_and_update_database("Super Buddies", 2013, None, None, "2014-04-30")
# make_api_calls_and_update_database("The Dark Knight Rises", 2012, 4, "Stupid ass Ra's al Ghul ruining my perfectly good conclusion to a trilogy. Anne Hathaway as Catwoman was very much meh, but Bane was incredible & I liked Joseph Gordon-Levitt as "'Robin'" (though that little reveal was stupid). Hated the twist & the ties back to stupid Liam Neeson but it was still good. Seeing Alfred cry & apoligize for failing the Wayne's almost broke me so I'm glad that was resolved. All-in-all it felt like an adequate send-off for the franchise. Talia undermines alot of the good parts of the movie, but I enjoyed everything prior to her reveal.", "2023-09-21")
# make_api_calls_and_update_database("The Dark Knight", 2008, 5, "Heath Ledger's Joker lived up to the hype and then some. The constant elevation of stakes kept the movie continuously teetering on the verge of collapse, and it never felt like the Joker could really be stopped. Harvey Dent's descent was the glue that held everything together in this movie. Narratively it had a very "'Empire Strikes Back'" vibe. Batman doesn't win. The Joker, in some sense, gets what he wants, only to really be "'defeated'" by Batman accepting defeat himself. The cinematography was there, the performances were unreal, and the narrative was as compelling as it gets. I didn't think I'd love it, but it lives up to the hype.", "2023-09-20")
# make_api_calls_and_update_database("Batman Begins", 2005, 3.5, "I'm not much of a Batman guy, but it came time for me to finally knock out all of the Bat-Movies. Batman Begins was a good movie, Cillian Murphy as Scarecrow was unexpectedly one of my favorite parts; however, Liam Neeson's Ra's al Ghul was absolutely not. Everyone knows a Batman origin story from one of the dozens of different interpretations, and I felt Nolan executed it really well, and told an interesting enough story to keep me interested. I still find the costume and the portrayal corny, Christian Bale's performance as Bruce Wayne was very good. Points deducted quite literally JUST for all of the weird Liam Neeson Ra's al Ghul stuff. Him being the villain at the end could not have disappointed me more.", "2023-09-20")
# make_api_calls_and_update_database("Birdman or (The Unexpected Virtue of Ignorance)", 2014, 4.5, "I really liked the entire movie but the third act was absolutely batshit strange. I didn't ever really peace together the "'superpower'" thing, and there were 3 suicide fakeouts in like 15 minutes at the end. I really don't know if Riggan lives or not. I understand why it's such a well-recieved film, but the whole third act took away from it for me. I really thought him dying on stage was a great conclusion, and even waking up to an unexpected success was excellent. But the final scene with his daughter at the window just made me confused.", "2023-09-20")
# make_api_calls_and_update_database("Elemental", 2023, 3.5, "I feel like I expected this to be worse than it actually was for some reason. The metaphor they were going for was pretty strong and clear-cut, and it was fairly well-executed but was also so up-front that it did make me question why we're telling a story about race with weird silly element characters instead of like, with people. Like I understand it's a children's movie but when the issues are uniquely human I don't think it's crazy to think we could've made the story about, well, humans. Wade was also dramatically unlikable for 90% of the movie, solely because he was just absolutely annoying the whole time. Also fuck Clod that guy sucked.", "2023-09-18")
# make_api_calls_and_update_database("Theater Camp", 2023, 5, "Very very good and sweet, and genuinely funny. The mockumentary style was done really well, and even though Ben Platt is weird and cringe I'll allow him one (1) succesfull and good movie since a bunch of The Bear cast is in this, and Jimmy Tatro is so good at being a dumb chud guy.", "2023-09-16")
# make_api_calls_and_update_database("About Last Night", 1986, 2.5, None, "2023-09-15")
# make_api_calls_and_update_database("Moonlight", 2016, 3, "Moonlight was good, and it was obviously critically recognized for good reasons. The cinematography and presentation of a coming-of-age story was excellent. It just wasn't for me; however. It was grounded and powerful, but ultimately still slow and without any real intruige. I'm struggling to define anything I would change or that I disliked about the film, but I struggle just as much to identify anything that I especially enjoyed.", "2023-09-14")
# make_api_calls_and_update_database("The Big Short", 2015, 3.5, "Interesting story and good learning opportunity, but altogether not that interesting of a movie.", "2023-09-11")
# make_api_calls_and_update_database("You Are So Not Invited to my Bat Mitzvah", 2023, 2, "Deeply deeply boring and not particularly interesting at all.", "2023-09-09")
# make_api_calls_and_update_database("Crazy, Stupid, Love", 2011, 3.5, "Above average, good time over all. Emma Stone + Ryan Gosling made me miss La La Land though.", "2023-09-09")
# make_api_calls_and_update_database("Licorice Pizza", 2021, 4.5, "I loved it, and a cute and silly slice-of-life romance is definitley in my wheelhouse. The age gap stuff kept it from 5★, for me. It just made me feel a little bit too uncomfy. It doesn't feel like this story changes much if Gary is 18 instead of 15. I understand the focus on how Alana needs to "'come of age'" more than Gary and how the age gaps with older men are used as relevant juxtoposition, it just didn't feel necessary for Gary to be 15 is all. The asian jokes were weird too and served ZERO purpose. Alana Haim was great, and the story way delightful and sweet.", "2023-09-08")
# make_api_calls_and_update_database("Nomadland", 2020, 3, "Good, but not particularly entertaining. Beautiful film making, and some of the most "'human'" scenes I've seen on the big screen. Ultimately though just felt a little too grounded to keep me interested.", "2023-09-07")
# make_api_calls_and_update_database("How to Train Your Dragon: The Hidden World", 2019, 4, "The weakest point of the franchise at large was, in my opinion, the villains. The third iteration delivered on a menacing villain, but the stakes were still more planted in the main character's journey. I loved all three movies, but my one complaint has to be the lack of real stakes from an enemy. Stoik's death was the only real "'consequence'" in the entire series, and that felt forced to make Hiccup the chief.", "2023-09-07")
# make_api_calls_and_update_database("How to Train Your Dragon 2", 2014, 4, None, "2023-09-06")
# make_api_calls_and_update_database("How to Train Your Dragon", 2010, 5, "My only real complaint was the animation quality and style could've definitley been better at times, but it feels wrong to detract from a 13-year-old movie for its animation quality. How to Train Your Dragon is a great film, and the Hiccup-Toothless relationship felt reminiscent of Hiro-Baymax from Big Hero 6, another favorite of mine. Something about a scrawny kid and his silly sidekick I guess.", "2023-09-05")
# make_api_calls_and_update_database("Barbie", 2023, 4, None, "2023-09-02")
# make_api_calls_and_update_database("The Trial of the Chicago 7", 2020, 4.5, "An excellent portrayal of a historical event I had little-to-no knowledge of. Sacha Baron Cohen was absolutely phenomonal in a more serious role, which was especially shocking for someone who only knows him from Borat and Talladega Nights. The cinematography was excellent, and the splicing of historical footage with cinematic re-creations was executed very well. I also thought Mark Rylance's performance as William Kuntsler was excellent.", "2023-09-02")
# make_api_calls_and_update_database("Nimona", 2023, 4.5, "I really enjoyed this movie, alot more than I expected. The emotional beats hit surprisingly hard, and the setting of a futuristic-medival-monster story was legitimateley cool. The first 30-40mins of the movie were a little slow, some of the humor didn't really land, and I really didn't love the animation, but the movie was really fun, sweet, and told a great story.", "2023-09-01")
# make_api_calls_and_update_database("Asteroid City", 2023, 4, "I can say with complete confidence that I did not understand this film, and yet strangely my enjoyment was not detered. While I felt the Grand Budapest Hotel was lacking in characterization, this film manages to excel, giving impressive depth to Augie, Midge,  the children, and even several supporting characters. The visuals are some of my favorite on film, the atmosphere created by Anderson's cinematographer, Robert D. Yeomen, by the use of sweeping camera motion and strange lighting effects, and the work of the set desingners to create such a visualy interesting environment cannot be overstated. Ultimately, while clearly telling a story that is not meant to be understood in a single sitting, the film manages to be charming, funny at times, and held my attention for the full run time. I was inspired to read an interview transcript with Yeomen about the film, and was taken by a quote: "'I read the script and shot the movie, but when I saw the movie, I saw connections that I had not made before.'" Asteroid City is strange and difficult to understand, but the film holds its own in every other way, and that should be commended.", "2023-08-31")
# make_api_calls_and_update_database("About Fate", 2022, 2.5, None, "2023-08-29")
# make_api_calls_and_update_database("Midnight in Paris", 2011, 2.5, "Just felt very boring. Very hard to connect to much of the story, and admittedly difficult to look at Owen Wilson as anything but... well, Owen Wilson.", "2023-08-28")
# make_api_calls_and_update_database("CODA", 2021, 5, "Nothing has ever made me cry as much as this movie made me cry. I don't honestly even know if I know why.", "2023-08-26")
# make_api_calls_and_update_database("The Boys", 2019, 5, None, None)
# make_api_calls_and_update_database("Reacher", 2022, 4, None, None)
# make_api_calls_and_update_database("The Truman Show", 1998, 4, None, "2023-08-24")
# make_api_calls_and_update_database("Spirited Away", 2001, 3.5, "I spent way too much of the film just feeling lost, and even a little bored.  I don't think the movie was bad in any way, it just really wasn't my taste. It's only my second Studio Ghibli film, and I just didn't enjoy it to the level I enjoyed Ponyo.", "2023-08-24")
# make_api_calls_and_update_database("The Imitation Game", 2014, 3.5, "This film benefits immensely from the fact that it's telling the incredibly interesting story of an incredible man, and it doesn't need to embelish that story for the big screen. I thought Benedict Cumberbatch's portrayal of Dr. Turing was excellent, and I enjoyed the film. However, there simply wasn't anything I felt the film did in that exceeded the story it was already going to tell.", "2023-08-23")
# make_api_calls_and_update_database("Teenage Mutant Ninja Turtles: Mutant Mayhem", 2023, 4.5, "Great characters, but underwhelming plot & villains. Having an entire cast of mutants introduced so late in the film didn't allow them to shine, especially with famous characters like Bebop and Rocksteady over-shadowing Superfly. The art direction was fantastic, and I think the second film that was teased with shredder will be even better.", "2023-08-22")
# make_api_calls_and_update_database("Soul", 2020, 3, "Soul just fell a little flat for me. Using monotone, bland environments & characters in the soul-dimension really took away from the story. I appreciated the grounded story of Joe's acceptance that music isn't his one true purpose, but trying to give Twenty-Two a "'grounded'" story was difficult when her character is just an ambiguous teal blob. Ultimately, I would have rather seen Joe's story unfold with regular human characters like Connie and Curly, and I don't understand why the focus was placed on Twenty-Two instead.", "2023-08-22")
# make_api_calls_and_update_database("Babylon", 2022, 4.5, "An exhaustingly long film that attempts to interconnect three films worth of story. I wanted to like this movie, but I didn't walk away happy with any of the stories it told, and each one would've done better without trying to interconnect the others. The 1920s feel was great, and the score was excellent, but there is probably an half-hour of unnecessary partying and orgies wrapped in to a movie that would've still been far too long without them. As time has passed since my first viewing, I can't neglect the fact that I have harshly underrated this film. It accomplishes so much through its score and its visuals, and despite a story that I found frustrating, it has remained more memorable than any film I've seen since. The film is in some sense unforgettable, the performances given by Margot Robbie, Brad Pitt, and Diego Calva are phenomonal, and the storys it tells, while frustratingly long and convoluted at times, are nevertheless exceptional.", "2023-08-21")
# make_api_calls_and_update_database("Star Wars Episode VII: The Force Awakens", 2015, 3.5, None, None)
# make_api_calls_and_update_database("Luca", 2021, 4, "A charming slice-of-life film that is among Pixar's best. My only complaint is that the the film's resolution feels incredibly rushed. Antonio's arrogance and jealousy of Luca and Julia is explained away by his father's death, but the train station scene wraps this storyline up nicely. However, the "'sea-monster'" portion of the plot felt like it was pushed aside quickly as a result.", "2023-08-21")
# make_api_calls_and_update_database("A Man Called Otto", 2022, 4.5, "A very sweet film which easily brings out tears. At times the film felt slow, and the building backstory of Otto & his wife felt like it was drawn out for an eternity, which made it diffficult to empathize with Otto for most of the film. However the last 30 minutes of the film are heart-wrenching, and the long run-time pays off in how well the relationships between Otto, Marisol, and Malcolm are developed.", "2023-08-20")
# make_api_calls_and_update_database("Modern Family", 2009, 5, None, None)
# make_api_calls_and_update_database("The Grand Budapest Hotel", 2014, 4, "A beautiful and visually interesting film that succeeds in telling an excellent story. Perhaps only because it's my first viewing of one of Anderson's films, but it was difficult to realy connect to many of the characters due to how "'unfamiliar'" the film's visuals were. The story was excellent, but the film lacked a "'human'" element.", "2023-08-20")
# make_api_calls_and_update_database("Cloak & Dagger", 2018, 3, None, None)
# make_api_calls_and_update_database("Emergence", 2019, 2, None, None)
# make_api_calls_and_update_database("Runaways", 2017, 3.5, None, None)
# make_api_calls_and_update_database("The Bear", 2022, 5, None, None)
# make_api_calls_and_update_database("Raising Hope", 2010, 3, None, None)
# make_api_calls_and_update_database("My Name is Earl", 2005, 3.5, None, None)
# make_api_calls_and_update_database("Disenchantment", 2018, 3.5, None, None)
# make_api_calls_and_update_database("13 Reasons Why", 2017, 3, None, None)
# make_api_calls_and_update_database("Designated Survivor", 2016, 5, None, None)
# make_api_calls_and_update_database("Mindhunter", 2017, 5, None, None)
# make_api_calls_and_update_database("The Crew", 2021, 1, None, None)
# make_api_calls_and_update_database("Sweet Tooth", 2021, 4, None, None)
# make_api_calls_and_update_database("Zoo", 2015, 3.5, None, None)
# make_api_calls_and_update_database("Kakegurui", 2017, 3.5, None, None)
# make_api_calls_and_update_database("Arcane", 2021, 5, None, None)
# make_api_calls_and_update_database("Space Force", 2020, 2.5, None, None)
# make_api_calls_and_update_database("Manifest", 2018, 3, None, None)
# make_api_calls_and_update_database("Luke Cage", 2016, 3.5, None, None)
# make_api_calls_and_update_database("Jessica Jones", 2015, 4, None, None)
# make_api_calls_and_update_database("Jericho", 2006, 4.5, None, None)
# make_api_calls_and_update_database("Baby Daddy", 2012, 3, None, None)
# make_api_calls_and_update_database("New Girl", 2011, 4.5, None, None)
# make_api_calls_and_update_database("Daredevil", 2015, 5, None, None)
# make_api_calls_and_update_database("Parks and Recreation", 2009, 4.5, None, None)
# make_api_calls_and_update_database("Brooklyn Nine-Nine", 2013, 5, None, None)
# make_api_calls_and_update_database("Timeless", 2016, 4, None, None)
# make_api_calls_and_update_database("Blindspot", 2015, 4, None, None)
# make_api_calls_and_update_database("Agents of S.H.I.E.L.D.", 2013, 5, None, None)
# make_api_calls_and_update_database("Coco", 2017, 4.5, "One of my favorite Pixar films, which boasts excellent stylized visuals that bring so much life and charm to the movie. The "'twist'" villain was the only weak point of the movie. I'm not sure turning him in to a one-dimensional "'murder bad guy'" was really necessary, and I felt it cheapened the payoff of Hector's memory being restored.", None)
# make_api_calls_and_update_database("Everything Everywhere All at Once", 2022, 5, None, None)
# make_api_calls_and_update_database("Knives Out", 2019, 5, None, None)
# make_api_calls_and_update_database("Spider-Man: Into the Spider-Verse", 2018, 5, None, None)
# make_api_calls_and_update_database("Get Out", 2017, 5, None, None)
# make_api_calls_and_update_database("Star Wars: Episode IV: A New Hope", 1977, 5, None, None)
# make_api_calls_and_update_database("Back to the Future", 1985, 5, None, None)
# make_api_calls_and_update_database("Nightcrawler", 2014, 5, None, "2020-11-02")
# make_api_calls_and_update_database("Star Wars: Episode V: The Empire Strikes Back", 1980, 5, None, None)
# make_api_calls_and_update_database("Puss in Boots: The Last Wish", 2022, 5, None, None)
# make_api_calls_and_update_database("Iron Man", 2008, 5, None, None)
# make_api_calls_and_update_database("Prisoners", 2013, 5, None, "2023-02-24")
# make_api_calls_and_update_database("Spider-Man: Across the Spider-Verse", 2023, 5, None, None)
# make_api_calls_and_update_database("Big Hero 6", 2014, 5, None, None)
# make_api_calls_and_update_database("The Lego Movie", 2014, 5, None, None)
# make_api_calls_and_update_database("Sorry to Bother You", 2018, 5, None, "2022-08-04")
# make_api_calls_and_update_database("Ponyo", 2008, 5, None, None)
# make_api_calls_and_update_database("The Mitchells vs. The Machines", 2021, 5, None, "2021-12-21")
# make_api_calls_and_update_database("RRR", 2022, 5, None, "2022-07-31")
# make_api_calls_and_update_database("BEEF", 2023, 5, None, None)
# make_api_calls_and_update_database("Hustle", 2022, 5, None, "2022-07-02")
# make_api_calls_and_update_database("Hamilton", 2020, 5, None, None)
# make_api_calls_and_update_database("Looking for Alaska", 2019, 5, None, None)
# make_api_calls_and_update_database("Whiplash", 2014, 5, None, None)
# make_api_calls_and_update_database("La La Land", 2016, 5, "Absolutely fucking tremendous.", None)
# make_api_calls_and_update_database("Ford v Ferrari", 2019, 5, None, None)
# make_api_calls_and_update_database("School of Rock", 2003, 4.5, None, None)
# make_api_calls_and_update_database("Cars", 2006, 4.5, None, None)
# make_api_calls_and_update_database("Monsters University", 2013, 4.5, None, None)
# make_api_calls_and_update_database("Moneyball", 2011, 4.5, None, None)
# make_api_calls_and_update_database("Cars 3", 2017, 4.5, None, None)
# make_api_calls_and_update_database("Hunt for the Wilderpeople", 2016, 4.5, None, "2020-10-29")
# make_api_calls_and_update_database("The Blind Side", 2009, 4.5, None, None)
# make_api_calls_and_update_database("Paul Blart: Mall Cop", 2009, 4.5, None, "2021-01-01")
# make_api_calls_and_update_database("The Karate Kid", 1984, 4.5, None, None)
# make_api_calls_and_update_database("Avengers: Infinity War", 2018, 4.5, None, None)
# make_api_calls_and_update_database("Avengers: Endgame", 2019, 4.5, None, None)
# make_api_calls_and_update_database("Spider-Man: No Way Home", 2021, 4.5, None, None)
# make_api_calls_and_update_database("Tetris", 2023, 4.5, None, None)
# make_api_calls_and_update_database("Rogue One: A Star Wars Story", 2016, 4.5, None, "2017-10-12")
# make_api_calls_and_update_database("Black Panther: Wakanda Forever", 2022, 4.5, None, None)
# make_api_calls_and_update_database("Parasite", 2019, 4.5, None, None)
# make_api_calls_and_update_database("The Incredibles", 2004, 4.5, None, None)
# make_api_calls_and_update_database("Encanto", 2021, 4.5, None, None)
# make_api_calls_and_update_database("Star Wars: Episode III: Revenge of the Sith", 2005, 4.5, None, None)
# make_api_calls_and_update_database("tick, tick...BOOM!", 2021, 4.5, None, "2021-12-27")
# make_api_calls_and_update_database("Chef", 2014, 4.5, None, None)
# make_api_calls_and_update_database("Game Night", 2018, 4.5, None, None)
# make_api_calls_and_update_database("The Bad Guys", 2022, 4.5, None, "2023-01-11")
# make_api_calls_and_update_database("Interstellar", 2014, 4, None, None)
# make_api_calls_and_update_database("Glass Onion", 2022, 4, None, "2023-01-01")
# make_api_calls_and_update_database("Scott Pilgrim vs. the World", 2010, 4, None, None)
# make_api_calls_and_update_database("Spider-Man: Homecoming", 2017, 4, None, None)
# make_api_calls_and_update_database("Deadpool", 2016, 4, None, None)
# make_api_calls_and_update_database("Spider-Man: Far from Home", 2019, 4, None, None)
# make_api_calls_and_update_database("The Avengers", 2012, 4, None, "2014-05-19")
# make_api_calls_and_update_database("Doctor Strange", 2016, 4, None, "2017-06-01")
# make_api_calls_and_update_database("Captain America: Civil War", 2016, 4, None, "2017-12-28")
# make_api_calls_and_update_database("The Breakfast Club", 1985, 4, None, None)
# make_api_calls_and_update_database("Jurassic Park", 1993, 4, None, None)
# make_api_calls_and_update_database("Guardians of the Galaxy Vol. 3", 2023, 4, None, None)
# make_api_calls_and_update_database("Star Wars: Episode VI: Return of the Jedi", 1983, 4, None, None)
# make_api_calls_and_update_database("Ant-Man", 2015, 4, None, None)
# make_api_calls_and_update_database("Ferris Bueller's Day Off", 1986, 4, None, None)
# make_api_calls_and_update_database("The Devil Wears Prada", 2006, 4, None, None)
# make_api_calls_and_update_database("Deadpool 2", 2018, 4, None, None)
# make_api_calls_and_update_database("Toy Story 3", 2010, 4, None, None)
# make_api_calls_and_update_database("E.T. the Extra-Terrestrial", 1982, 4, None, None)
# make_api_calls_and_update_database("When Harry Met Sally...", 1989, 4, None, None)
# make_api_calls_and_update_database("Kung Fu Panda", 2008, 4, None, None)
# make_api_calls_and_update_database("Legally Blonde", 2001, 4, None, None)
# make_api_calls_and_update_database("Ghostbusters", 1984, 4, None, None)
# make_api_calls_and_update_database("Crazy Rich Asians", 2018, 4, None, None)
# make_api_calls_and_update_database("Pitch Perfect", 2012, 4, None, None)
# make_api_calls_and_update_database("Dungeons & Dragons: Honor Among Thieves", 2023, 4, None, None)
# make_api_calls_and_update_database("Pokémon Detective Pikachu", 2019, 4, None, None)
# make_api_calls_and_update_database("Murder Mystery 2", 2023, 4, None, "2023-04-01")
# make_api_calls_and_update_database("Moon Knight", 2022, 4, None, None)
# make_api_calls_and_update_database("Sonic the Hedgehog 2", 2022, 4, None, None)
# make_api_calls_and_update_database("Fyre", 2019, 4, None, None)
# make_api_calls_and_update_database("Pepsi, Where's My Jet?", 2022, 4, None, None)
# make_api_calls_and_update_database("Toradora!", 2008, 4, None, None)
# make_api_calls_and_update_database("Sonic the Hedgehog", 2020, 4, None, None)
# make_api_calls_and_update_database("Happy Gilmore", 1996, 4, None, None)
# make_api_calls_and_update_database("Kung Fu Panda 3", 2016, 4, None, "2017-01-20")
# make_api_calls_and_update_database("Rush", 2013, 4, None, "2021-10-25")
# make_api_calls_and_update_database("DodgeBall: A True Underdog Story", 2004, 4, None, None)
# make_api_calls_and_update_database("Phineas and Ferb: The Movie: Across the 2nd Dimension", 2011, 4, None, "2015-08-16")
# make_api_calls_and_update_database("The Karate Kid Part II", 1986, 4, None, None)
# make_api_calls_and_update_database("They Cloned Tyrone", 2023, 4, None, None)
# make_api_calls_and_update_database("Logan Lucky", 2017, 4, None, None)
# make_api_calls_and_update_database("Incredibles 2", 2018, 3.5, None, None)
# make_api_calls_and_update_database("Black Panther", 2018, 4, None, None)
# make_api_calls_and_update_database("Thor: Ragnarok", 2017, 4, None, "2018-06-09")
# make_api_calls_and_update_database("Air", 2023, 4, None, None)
# make_api_calls_and_update_database("Drumline", 2002, 4, None, None)
# make_api_calls_and_update_database("Untold: The Girlfriend Who Didn't Exist", 2022, 4, None, None)
# make_api_calls_and_update_database("Megamind", 2010, 4, None, None)
# make_api_calls_and_update_database("Monsters, Inc.", 2001, 4, None, None)
# make_api_calls_and_update_database("Wreck-It Ralph", 2012, 4, None, None)
# make_api_calls_and_update_database("WandaVision", 2021, 4, None, None)
# make_api_calls_and_update_database("Eurovision Song Contest: The Story of Fire Saga", 2020, 4, None, "2021-02-21")
# make_api_calls_and_update_database("Talladega Nights: The Ballad of Ricky Bobby", 2006, 4, None, "2021-10-01")
# make_api_calls_and_update_database("Nope", 2022, 4, None, None)
# make_api_calls_and_update_database("Ratatouille", 2007, 4, None, None)
# make_api_calls_and_update_database("Mean Girls", 2004, 4, None, None)
# make_api_calls_and_update_database("Home Alone", 1990, 4, None, None)
# make_api_calls_and_update_database("Moana", 2016, 3.5, None, None)
# make_api_calls_and_update_database("Free Guy", 2021, 3.5, None, None)
# make_api_calls_and_update_database("The Greatest Showman", 2017, 3.5, None, None)
# make_api_calls_and_update_database("Despicable Me", 2010, 3.5, None, None)
# make_api_calls_and_update_database("Zoolander", 2001, 3.5, None, "2015-10-28")
# make_api_calls_and_update_database("The Parent Trap", 1998, 3.5, None, None)
# make_api_calls_and_update_database("The Bob's Burgers Movie", 2022, 3.5, None, None)
# make_api_calls_and_update_database("She-Hulk: Attorney at Law", 2022, 3.5, None, None)
# make_api_calls_and_update_database("Freaky", 2020, 3.5, None, None)
# make_api_calls_and_update_database("Murder Mystery", 2019, 3.5, None, "2020-03-22")
# make_api_calls_and_update_database("50 First Dates", 2004, 3.5, None, "2015-05-29")
# make_api_calls_and_update_database("Click", 2006, 3.5, None, None)
# make_api_calls_and_update_database("The Wedding Singer", 1998, 3.5, None, "2015-10-27")
# make_api_calls_and_update_database("Billy Madison", 1995, 3.5, None, "2015-11-15")
# make_api_calls_and_update_database("The Guilty", 2021, 3.5, None, None)
# make_api_calls_and_update_database("The Internship", 2013, 3.5, None, None)
# make_api_calls_and_update_database("Rudy", 1993, 3.5, None, None)
# make_api_calls_and_update_database("Rise of the Planet of the Apes", 2011, 3.5, None, None)
# make_api_calls_and_update_database("The Muppets", 2011, 3.5, None, None)
# make_api_calls_and_update_database("We Bought a Zoo", 2011, 3.5, None, None)
# make_api_calls_and_update_database("Austin Powers: International Man of Mystery", 1997, 3.5, None, None)
# make_api_calls_and_update_database("WALL·E", 2008, 3.5, None, None)
# make_api_calls_and_update_database("Robots", 2005, 3.5, None, None)
# make_api_calls_and_update_database("Popstar: Never Stop Never Stopping", 2016, 3.5, None, None)
# make_api_calls_and_update_database("Guardians of the Galaxy Vol. 2", 2017, 3.5, None, "2017-12-28")
# make_api_calls_and_update_database("Ant-Man and the Wasp", 2018, 3.5, None, None)
# make_api_calls_and_update_database("Frozen", 2013, 3.5, None, None)
# make_api_calls_and_update_database("Hotel Artemis", 2018, 3.5, None, None)
# make_api_calls_and_update_database("Turning Red", 2022, 3.5, None, None)
# make_api_calls_and_update_database("Captain Marvel", 2019, 3.5, None, None)
# make_api_calls_and_update_database("Back to the Future Part II", 1989, 3.5, None, None)
# make_api_calls_and_update_database("Home Alone 2: Lost in New York", 1992, 3.5, None, None)
# make_api_calls_and_update_database("The Falcon and the Winter Soldier", 2021, 3.5, None, None)
# make_api_calls_and_update_database("The Intern", 2015, 3.5, None, None)
# make_api_calls_and_update_database("The Lego Movie 2: The Second Part", 2019, 3.5, None, None)
# make_api_calls_and_update_database("Austin Powers: The Spy Who Shagged Me", 1999, 3.5, None, None)
# make_api_calls_and_update_database("Ms. Marvel", 2022, 3.5, None, None)
# make_api_calls_and_update_database("Harold & Kumar Go to White Castle", 2004, 3.5, None, None)
# make_api_calls_and_update_database("Day Shift", 2022, 3.5, None, None)
# make_api_calls_and_update_database("Uncut Gems", 2019, 3.5, None, "2020-05-26")
# make_api_calls_and_update_database("Thor: Love and Thunder", 2022, 3.5, None, None)
# make_api_calls_and_update_database("The Super Mario Bros. Movie", 2023, 3.5, None, None)
# make_api_calls_and_update_database("Flamin' Hot", 2023, 3.5, None, None)
# make_api_calls_and_update_database("Hawkeye", 2021, 3.5, None, None)
# make_api_calls_and_update_database("Mrs. Doubtfire", 1993, 3.5, None, None)
# make_api_calls_and_update_database("Lemonade Mouth", 2011, 3.5, None, "2017-05-14")
# make_api_calls_and_update_database("The Menu", 2022, 3, None, None)
# make_api_calls_and_update_database("Don't Look Up", 2021, 3, None, "2021-12-27")
# make_api_calls_and_update_database("Doctor Strange in the Multiverse of Madness", 2022, 3, None, None)
# make_api_calls_and_update_database("The Suicide Squad", 2021, 3, None, None)
# make_api_calls_and_update_database("Iron Man 3", 2013, 3, None, None)
# make_api_calls_and_update_database("Iron Man 2", 2010, 3, None, None)
# make_api_calls_and_update_database("Missing", 2023, 3, None, None)
# make_api_calls_and_update_database("The Hatchet Wielding Hitchhiker", 2023, 3, None, None)
# make_api_calls_and_update_database("Red Notice", 2021, 3, None, "2021-11-18")
# make_api_calls_and_update_database("Sing 2", 2021, 3, None, None)
# make_api_calls_and_update_database("Ron's Gone Wrong", 2021, 3, None, None)
# make_api_calls_and_update_database("Schumacher", 2021, 3, None, None)
# make_api_calls_and_update_database("Pixels", 2015, 3, None, None)
# make_api_calls_and_update_database("Anger Management", 2003, 3, None, "2015-05-19")
# make_api_calls_and_update_database("Avengers: Age of Ultron", 2015, 3, None, None)
# make_api_calls_and_update_database("Eddie the Eagle", 2015, 3, None, None)
# make_api_calls_and_update_database("Despicable Me 2", 2013, 3, None, None)
# make_api_calls_and_update_database("Meet Dave", 2008, 3, None, None)
# make_api_calls_and_update_database("White Chicks", 2004, 3, None, "2016-03-07")
# make_api_calls_and_update_database("The Good Nurse", 2022, 3, None, "2022-11-12")
# make_api_calls_and_update_database("Drumline: A New Beat", 2014, 3, None, "2015-09-19")
# make_api_calls_and_update_database("Renfield", 2023, 3, None, None)
# make_api_calls_and_update_database("Emily the Criminal", 2022, 3, None, None)
# make_api_calls_and_update_database("Anchorman: The Legend of Ron Burgundy", 2004, 3, None, None)
# make_api_calls_and_update_database("Pitch Perfect 2", 2015, 3, None, None)
# make_api_calls_and_update_database("Field of Dreams", 1989, 3, None, None)
# make_api_calls_and_update_database("I Am Mother", 2019, 3, None, "2019-10-23")
# make_api_calls_and_update_database("The Pink Panther", 2006, 3, None, None)
# make_api_calls_and_update_database("Invincible", 2006, 3, None, None)
# make_api_calls_and_update_database("Ralph Breaks the Internet", 2018, 3, None, "2020-02-23")
# make_api_calls_and_update_database("Palm Springs", 2020, 3, None, None)
# make_api_calls_and_update_database("Solo: A Star Wars Story", 2018, 2.5, None, None)
# make_api_calls_and_update_database("Elf", 2003, 2.5, None, None)
# make_api_calls_and_update_database("Onward", 2020, 2.5, None, None)
# make_api_calls_and_update_database("You People", 2023, 2.5, None, None)
# make_api_calls_and_update_database("Bad Trip", 2021, 2.5, None, None)
# make_api_calls_and_update_database("Tom & Jerry", 2021, 2.5, None, None)
# make_api_calls_and_update_database("Aladdin", 2019, 2.5, None, None)
# make_api_calls_and_update_database("The Cobbler", 2014, 2.5, None, "2015-06-22")
# make_api_calls_and_update_database("Daddy's Home", 2015, 2.5, None, None)
# make_api_calls_and_update_database("Despicable Me 3", 2017, 2.5, None, None)
# make_api_calls_and_update_database("Mr. Peabody & Sherman", 2014, 2.5, None, None)
# make_api_calls_and_update_database("The Amazing Spider-Man", 2012, 2.5, None, None)
# make_api_calls_and_update_database("Cars 2", 2011, 2.5, None, None)
# make_api_calls_and_update_database("Radio Rebel", 2012, 2.5, None, "2014-05-31")
# make_api_calls_and_update_database("The Out-Laws", 2023, 2.5, None, None)
# make_api_calls_and_update_database("Guns Akimbo", 2019, 2.5, None, None)
# make_api_calls_and_update_database("Black Widow", 2021, 2.5, None, None)
# make_api_calls_and_update_database("Eternals", 2021, 2.5, None, None)
# make_api_calls_and_update_database("The Other Guys", 2010, 2.5, None, "2020-03-22")
# make_api_calls_and_update_database("Game Over, Man!", 2018, 2.5, None, "2022-03-04")
# make_api_calls_and_update_database("Here Comes the Boom", 2012, 2.5, None, "2021-12-06")
# make_api_calls_and_update_database("Don't Worry Darling", 2022, 2.5, None, None)
# make_api_calls_and_update_database("Ant-Man and the Wasp: Quantumania", 2023, 2.5, None, "2019-03-20")
# make_api_calls_and_update_database("Jurassic World", 2015, 2.5, None, None)
# make_api_calls_and_update_database("Star Wars: Episode VIII: The Last Jedi", 2017, 2, None, None)
# make_api_calls_and_update_database("Elvis", 2022, 2, None, None)
# make_api_calls_and_update_database("Star Wars: Episode IX: The Rise of Skywalker", 2019, 2, None, None)
# make_api_calls_and_update_database("Star Wars: Episode I: The Phantom Menace", 1999, 2, None, None)
# make_api_calls_and_update_database("21 Jump Street", 2012, 2, None, None)
# make_api_calls_and_update_database("Jumanji: The Next Level", 2019, 2, None, None)
# make_api_calls_and_update_database("The Do-Over", 2016, 2, None, "2022-12-13")
# make_api_calls_and_update_database("Spenser Confidential", 2020, 2, None, "2020-03-19")
# make_api_calls_and_update_database("Descendants 2", 2017, 2, None, None)
# make_api_calls_and_update_database("The Defenders", 2017, 2, None, None)
# make_api_calls_and_update_database("Sing", 2016, 2, None, "2017-09-11")
# make_api_calls_and_update_database("Rio", 2011, 2, None, None)
# make_api_calls_and_update_database("Turbo", 2013, 2, None, None)
# make_api_calls_and_update_database("Shang-Chi and the Legend of the Ten Rings", 2021, 2, None, None)
# make_api_calls_and_update_database("White Noise", 2022, 2, None, None)
# make_api_calls_and_update_database("Reality", 2023, 2, None, None)
# make_api_calls_and_update_database("Star Wars: Episode II: Attack of the Clones", 2002, 2, None, None)
# make_api_calls_and_update_database("Suicide Squad", 2016, 1.5, None, None)
# make_api_calls_and_update_database("Cocaine Bear", 2023, 1.5, None, None)
# make_api_calls_and_update_database("The Wrong Missy", 2020, 1.5, None, None)
# make_api_calls_and_update_database("The Hustle", 2019, 1.5, None, None)
# make_api_calls_and_update_database("Spanglish", 2004, 1.5, None, "2015-10-11")
# make_api_calls_and_update_database("Sandy Wexler", 2017, 1.5, None, "2022-01-22")
# make_api_calls_and_update_database("Secret Invasion", 2023, 1.5, None, None)
# make_api_calls_and_update_database("Thor", 2011, 1, None, None)
# make_api_calls_and_update_database("Thor: The Dark World", 2013, 1, None, None)
# make_api_calls_and_update_database("The Amazing Spider-Man 2", 2014, 1, None, None)
# make_api_calls_and_update_database("The Polar Express", 2004, 1, None, None)
# make_api_calls_and_update_database("Inside", 2023, 1, None, None)
# make_api_calls_and_update_database("Tall Girl", 2019, 1, None, None)
# make_api_calls_and_update_database("Jack and Jill", 2011, 1, None, None)
# make_api_calls_and_update_database("Horton Hears a Who!", 2008, 1, None, None)
# make_api_calls_and_update_database("Kindergarten Cop 2", 2016, 1, None, "2016-06-02")
# make_api_calls_and_update_database("Mulan", 2020, 1, None, None)
# make_api_calls_and_update_database("Hubie Halloween", 2020, 0.5, None, "2022-11-13")
# make_api_calls_and_update_database("Yoga Hosers", 2016, 0.5, None, None)
# make_api_calls_and_update_database("Zoom", 2006, 0.5, None, None)
# make_api_calls_and_update_database("Bedtime Stories", 2008, None, None, None)
# make_api_calls_and_update_database("Tucker and Dale vs. Evil", 2010, None, None, None)
# make_api_calls_and_update_database("Harry Potter and the Deathly Hallows: Part 1", 2010, None, None, None)
# make_api_calls_and_update_database("Rango", 2011, None, None, None)
# make_api_calls_and_update_database("Harry Potter and the Deathly Hallows: Part 2", 2011, None, None, None)
# make_api_calls_and_update_database("Avatar", 2009, None, None, None)
# make_api_calls_and_update_database("Harry Potter and the Half-Blood Prince", 2009, None, None, None)
# make_api_calls_and_update_database("Ice Age: Dawn of the Dinosaurs", 2009, None, None, None)
# make_api_calls_and_update_database("Alvin and the Chipmunks: The Squeakquel", 2009, None, None, None)
# make_api_calls_and_update_database("Wizards of Waverly Place: The Movie", 2009, None, None, None)
# make_api_calls_and_update_database("Planet 51", 2009, None, None, None)
# make_api_calls_and_update_database("Space Buddies", 2009, None, None, None)
# make_api_calls_and_update_database("Air Buddies", 2006, None, None, None)
# make_api_calls_and_update_database("Snow Buddies", 2008, None, None, None)
# make_api_calls_and_update_database("Santa Buddies", 2009, None, None, None)
# make_api_calls_and_update_database("Spooky Buddies", 2011, None, None, None)
# make_api_calls_and_update_database("Treasure Buddies", 2012, None, None, None)
# make_api_calls_and_update_database("Hatching Pete", 2009, None, None, "2014-06-02")
# make_api_calls_and_update_database("Prep & Landing", 2009, None, None, None)
# make_api_calls_and_update_database("Ace Ventura: Pet Detective", 1994, None, None, None)
# make_api_calls_and_update_database("Spaceballs", 1987, None, None, None)
# make_api_calls_and_update_database("Bolt", 2008, None, None, None)
# make_api_calls_and_update_database("Madagascar: Escape 2 Africa", 2008, None, None, None)
# make_api_calls_and_update_database("High School Musical 3: Senior Year", 2008, None, None, None)
# make_api_calls_and_update_database("Journey to the Center of the Earth", 2008, None, None, None)
# make_api_calls_and_update_database("Open Season 2", 2008, None, None, None)
# make_api_calls_and_update_database("Harry Potter and the Order of the Phoenix", 2007, None, None, None)
# make_api_calls_and_update_database("Harry Potter and the Prisoner of Azkaban", 2004, None, None, None)
# make_api_calls_and_update_database("Harry Potter and the Sorcerer's Stone", 2001, None, None, None)
# make_api_calls_and_update_database("Harry Potter and the Goblet of Fire", 2005, None, None, None)
# make_api_calls_and_update_database("Harry Potter and the Chamber of Secrets", 2002, None, None, None)
# make_api_calls_and_update_database("High School Musical 2", 2007, None, None, None)
# make_api_calls_and_update_database("Madagascar", 2005, None, None, None)
# make_api_calls_and_update_database("The Adventures of Sharkboy and Lavagirl", 2005, None, None, None)
# make_api_calls_and_update_database("Daddy Day Care", 2003, None, None, "2016-11-11")
# make_api_calls_and_update_database("Kindergarten Cop", 1990, None, None, None)
# make_api_calls_and_update_database("The Karate Kid Part III", 1989, None, None, None)
# make_api_calls_and_update_database("Back to the Future Part III", 1990, None, None, None)
# make_api_calls_and_update_database("Shrek 2", 2004, None, None, None)
# make_api_calls_and_update_database("The SpongeBob SquarePants Movie", 2004, None, None, None)
# make_api_calls_and_update_database("Super Size Me", 2004, None, None, None)
# make_api_calls_and_update_database("Finding Nemo", 2003, None, None, None)
# make_api_calls_and_update_database("Spy Kids 3", 2003, None, None, None)
# make_api_calls_and_update_database("Spy Kids", 2001, None, None, None)
# make_api_calls_and_update_database("Spy Kids 2", 2002, None, None, None)
# make_api_calls_and_update_database("Coin Heist", 2017, None, None, "2017-01-23")
# make_api_calls_and_update_database("Flubber", 1997, None, None, "2016-11-12")
# make_api_calls_and_update_database("Night at the Museum", 2006, None, None, None)
# make_api_calls_and_update_database("Happy Feet", 2006, None, None, None)
# make_api_calls_and_update_database("Dead Poets Society", 1989, None, None, None)
# make_api_calls_and_update_database("The Starving Games", 2013, None, None, None)
# make_api_calls_and_update_database("Pokemon the Movie: Kyurem vs. the Sword of Justice", 2012, None, None, None)
# make_api_calls_and_update_database("Pants on Fire", 2014, None, None, "2015-08-14")
# make_api_calls_and_update_database("Penguins of Madagascar", 2014, None, None, "2015-08-06")
# make_api_calls_and_update_database("Ping Pong Playa", 2007, None, None, "2015-05-19")
# make_api_calls_and_update_database("The Benchwarmers", 2006, None, None, "2015-05-21")
# make_api_calls_and_update_database("The Longest Yard", 2005, None, None, "2015-05-23")
# make_api_calls_and_update_database("Minutemen", 2008, None, None, "2014-06-01")
# make_api_calls_and_update_database("The Croods", 2013, None, None, "2014-06-01")
# make_api_calls_and_update_database("Cloud 9", 2014, None, None, "2014-05-30")
# make_api_calls_and_update_database("Free Birds", 2013, None, None, "2014-05-29")
# make_api_calls_and_update_database("FRED 3: Camp Fred", 2012, None, None, "2014-03-26")
# make_api_calls_and_update_database("Fred 2: Night of the Living Fred", 2011, None, None, "2014-03-25")
# make_api_calls_and_update_database("FRED: The Movie", 2010, None, None, "2014-03-25")
# make_api_calls_and_update_database("Leroy & Stitch", 2006, None, None, "2014-01-03")
# make_api_calls_and_update_database("Lilo & Stitch 2: Stitch Has a Glitch", 2005, None, None, "2014-01-03")
# make_api_calls_and_update_database("Stitch! The Movie", 2003, None, None, "2014-01-03")
# make_api_calls_and_update_database("The Lorax", 2012, None, None, "2014-03-19")
# make_api_calls_and_update_database("Rookie of the Year", 1993, None, None, None)
# make_api_calls_and_update_database("Planet of the Apes", 1968, None, None, None)
# make_api_calls_and_update_database("Beneath the Planet of the Apes", 1970, None, None, None)
# make_api_calls_and_update_database("Escape from the Planet of the Apes", 1971, None, None, None)
# make_api_calls_and_update_database("Conquest of the Planet of the Apes", 1972, None, None, None)
# make_api_calls_and_update_database("Toy Story", 1995, None, None, None)
# make_api_calls_and_update_database("Up", 2009, None, None, None)
# make_api_calls_and_update_database("Finding Dory", 2016, None, None, "2017-07-03")
# make_api_calls_and_update_database("Toy Story 2", 1999, None, None, None)
# make_api_calls_and_update_database("The Little Mermaid", 1989, None, None, None)
# make_api_calls_and_update_database("Beauty and the Beast", 1991, None, None, None)
# make_api_calls_and_update_database("The Lion King", 1994, None, None, None)
# make_api_calls_and_update_database("The Hunchback of Notre Dame", 1996, None, None, None)
# make_api_calls_and_update_database("Hercules", 1997, None, None, None)
# make_api_calls_and_update_database("Chicken Little", 2005, None, None, None)
# make_api_calls_and_update_database("Meet the Robinsons", 2007, None, None, None)